### ISSUE TITLE
[Feature] Add support for update deployments

### ISSUE THREAD

**Issue by ankitrgadiya** [rapyuta-robotics/rapyuta-io-sdk#11]
Rapyuta.io supports updating the running deployment. This is helpful when a Build is re-triggered and it builds a new image, in which case updating the deployment will swap the currently running container with a new one using the newly built image.

This support is absent in the SDK and automating this flow is difficult for users.

API: https://gadocs.apps.rapyuta.io/#/Deployment/UpdateServiceInstance

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=894406795)

**Comment by pallabpain** [comment]
Not relevant anymore since code has been moved to v2client in the CLI.
