### ISSUE TITLE
[Request] Support for executing commands in Cloud Deployments

### ISSUE THREAD

**Issue by amitsingh21** [rapyuta-robotics/rapyuta-io-sdk#16]
https://rapyuta-robotics.slack.com/archives/C15ES2LQP/p1653016624526079

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=901389812)

**Comment by pallabpain** [comment]
This is no longer valid. We do not support executing commands on cloud deployments.
